//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Captures {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MenuLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MenuLang() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Captures.MenuLang", typeof(MenuLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionnez une zone de l&apos;écran en glissant la souris.
        /// </summary>
        internal static string Area_Label {
            get {
                return ResourceManager.GetString("Area_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La capture a réussie..
        /// </summary>
        internal static string Capture_Sucess {
            get {
                return ResourceManager.GetString("Capture_Sucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La capture à échouée !.
        /// </summary>
        internal static string Captures_Fail {
            get {
                return ResourceManager.GetString("Captures_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Afficher Captures.
        /// </summary>
        internal static string Context_Show {
            get {
                return ResourceManager.GetString("Context_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisissez le dossier des captures.
        /// </summary>
        internal static string Dialog_ChooseFolder {
            get {
                return ResourceManager.GetString("Dialog_ChooseFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à élément.
        /// </summary>
        internal static string Element {
            get {
                return ResourceManager.GetString("Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à éléments.
        /// </summary>
        internal static string ElementP {
            get {
                return ResourceManager.GetString("ElementP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur, l&apos;image \&quot;{Name}\&quot; est inaccessible !.
        /// </summary>
        internal static string Error_AccessFile {
            get {
                return ResourceManager.GetString("Error_AccessFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le dossier des captures est inaccessible !.
        /// </summary>
        internal static string Error_AccessFolder {
            get {
                return ResourceManager.GetString("Error_AccessFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur, impossible de supprimer l&apos;image \&quot;{Name}\&quot; !.
        /// </summary>
        internal static string Error_DelFile {
            get {
                return ResourceManager.GetString("Error_DelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur, le dossier des captures est introuvable !.
        /// </summary>
        internal static string Error_FindFolder {
            get {
                return ResourceManager.GetString("Error_FindFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Problème de librairie interne ! Merci de contacter les développeurs ;).
        /// </summary>
        internal static string Error_Lib {
            get {
                return ResourceManager.GetString("Error_Lib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun dossier n&apos;a été sélectionné !.
        /// </summary>
        internal static string Error_NoFolder {
            get {
                return ResourceManager.GetString("Error_NoFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur, cette touche est déjà utilisée pour la capture complète !.
        /// </summary>
        internal static string Error_UsedAlls {
            get {
                return ResourceManager.GetString("Error_UsedAlls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur, cette touche est déjà utilisée pour la capture de zone !.
        /// </summary>
        internal static string Error_UsedArea {
            get {
                return ResourceManager.GetString("Error_UsedArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur, cette touche est déjà utilisée pour la capture de fenêtre !.
        /// </summary>
        internal static string Error_UsedWin {
            get {
                return ResourceManager.GetString("Error_UsedWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chargement.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Maximum.
        /// </summary>
        internal static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Minimum.
        /// </summary>
        internal static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouveau.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à sélectionnée.
        /// </summary>
        internal static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à sélectionnées.
        /// </summary>
        internal static string SelectedP {
            get {
                return ResourceManager.GetString("SelectedP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible de vérifier les mise à jours !.
        /// </summary>
        internal static string Update_Fail {
            get {
                return ResourceManager.GetString("Update_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous possédez déjà la dernière version !.
        /// </summary>
        internal static string Update_None {
            get {
                return ResourceManager.GetString("Update_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une mise à jour est disponible, voulez vous la télécharger ?.
        /// </summary>
        internal static string Update_Valaible {
            get {
                return ResourceManager.GetString("Update_Valaible", resourceCulture);
            }
        }
    }
}
